#!/bin/bash
# Install "da" CLI wrapper — puts the dosagent client on your PATH
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# --- Uninstall ---
if [ "$1" = "--uninstall" ]; then
    found=0
    for dir in "$HOME/.local/bin" "$HOME/bin" "/usr/local/bin"; do
        for name in "$dir"/da "$dir"/dosagent; do
            if [ -f "$name" ] && grep -q "$PROJECT_DIR" "$name" 2>/dev/null; then
                rm -f "$name"
                echo "Removed $name"
                found=1
            fi
        done
    done
    if [ -f "$HOME/.config/dosagent.conf" ]; then
        rm -f "$HOME/.config/dosagent.conf"
        echo "Removed $HOME/.config/dosagent.conf"
    fi
    if [ "$found" -eq 0 ]; then
        echo "Nothing to uninstall: no wrapper found for $PROJECT_DIR"
    else
        echo "Client wrapper uninstalled."
    fi
    exit 0
fi

# --- Install ---

DEFAULT_DIR="$HOME/.local/bin"
DEFAULT_NAME="da"

echo ""
echo "Install the 'da' command so you can run it from anywhere."
echo ""

# Prompt for install directory
printf "Install directory [%s]: " "$DEFAULT_DIR"
read -r INSTALL_DIR
INSTALL_DIR="${INSTALL_DIR:-$DEFAULT_DIR}"

# Expand ~ if the user typed it literally
INSTALL_DIR="${INSTALL_DIR/#\~/$HOME}"

# Prompt for command name
printf "Command name [%s]: " "$DEFAULT_NAME"
read -r CMD_NAME
CMD_NAME="${CMD_NAME:-$DEFAULT_NAME}"

# Validate command name
if [[ "$CMD_NAME" =~ [/[:space:]] ]]; then
    echo "ERROR: Command name cannot contain slashes or spaces" >&2
    exit 1
fi

TARGET="$INSTALL_DIR/$CMD_NAME"

# Create directory if needed
if [ ! -d "$INSTALL_DIR" ]; then
    printf "%s does not exist. Create it? [Y/n]: " "$INSTALL_DIR"
    read -r CREATE
    case "$CREATE" in
        [nN]*)
            echo "Aborted."
            exit 1
            ;;
    esac
    mkdir -p "$INSTALL_DIR"
    echo "Created $INSTALL_DIR"
fi

# Check for existing file
if [ -f "$TARGET" ]; then
    printf "%s already exists. Overwrite? [Y/n]: " "$TARGET"
    read -r OVERWRITE
    case "$OVERWRITE" in
        [nN]*)
            echo "Aborted."
            exit 1
            ;;
    esac
fi

# Write the wrapper script
cat > "$TARGET" << WRAPPER
#!/bin/sh
# Generated by dosagent/scripts/install_client.sh — do not edit
export PYTHONPATH="$PROJECT_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
exec python3 -m client.daclient "\$@"
WRAPPER
chmod +x "$TARGET"

echo "Installed $TARGET"

# Warn if not on PATH
case ":$PATH:" in
    *":$INSTALL_DIR:"*)
        ;;
    *)
        echo ""
        echo "WARNING: $INSTALL_DIR is not in your PATH."
        echo "Add this to your shell profile (~/.bashrc or ~/.zshrc):"
        echo ""
        echo "  export PATH=\"$INSTALL_DIR:\$PATH\""
        echo ""
        ;;
esac

# --- Configure default host/port ---

CONFIG_FILE="$HOME/.config/dosagent.conf"
WRITE_CONFIG=1

if [ -f "$CONFIG_FILE" ]; then
    printf "\n%s already exists. Overwrite? [y/N]: " "$CONFIG_FILE"
    read -r OVERWRITE_CFG
    case "$OVERWRITE_CFG" in
        [yY]*) ;;
        *) WRITE_CONFIG=0 ;;
    esac
fi

if [ "$WRITE_CONFIG" -eq 1 ]; then
    echo ""
    echo "Configure default connection settings."

    # Prompt for host
    while true; do
        printf "Agent host [localhost]: "
        read -r CFG_HOST
        CFG_HOST="${CFG_HOST:-localhost}"
        if [ -z "$CFG_HOST" ] || echo "$CFG_HOST" | grep -q '[[:space:]]'; then
            echo "ERROR: Host cannot be empty or contain whitespace" >&2
            continue
        fi
        break
    done

    # Prompt for port
    while true; do
        printf "Agent port [10000]: "
        read -r CFG_PORT
        CFG_PORT="${CFG_PORT:-10000}"
        if ! echo "$CFG_PORT" | grep -qE '^[0-9]+$'; then
            echo "ERROR: Port must be an integer" >&2
            continue
        fi
        if [ "$CFG_PORT" -lt 1 ] || [ "$CFG_PORT" -gt 65535 ]; then
            echo "ERROR: Port must be between 1 and 65535" >&2
            continue
        fi
        break
    done

    mkdir -p "$HOME/.config"
    cat > "$CONFIG_FILE" << CONF
[agent]
host = $CFG_HOST
port = $CFG_PORT
CONF
    echo "Wrote $CONFIG_FILE"
fi

echo "Done. Run '$CMD_NAME' to connect to DOSAGENT."
